default:
  domain: "kefych.net"
  base_media_url: "/"
  category: "Christian"
  author: "GJCC"
  generator: "rss_writer"
  server_name: "file-vm"
  base_file_path: "/home/mchu"
  base_output_path: "/ntc/tmp"
channels:
  en:
    videos-all:
      title: "ACP GJCC Videos"
      link: "https://file.ziongjcc.org/Video"
      description: "GJCC Spritual Flow - All Videos"
      language: "en-us"
      file_path: "/home/mchu/Videos/ZSF"
      filter_extension: ".mp4"
      output_path: "/ntc/tmp/en-videos.rss"
    audio-chi:
      title: "ACP GJCC Chinese Audio"
      link: "https://file.ziongjcc.org/Audio/chinese"
      description: "GJCC Spritual Flow - Chinese Audio"
      language: "zh-tw"
      file_path: "/home/mchu/Music/ZSF/Chinese"
      filter_extension: ".mp3"
      output_path: "/ntc/tmp/en-audio-chi.rss"
    audio-eng:
      title: "ACP GJCC English Audio"
      link: "https://file.ziongjcc.org/Audio/english"
      description: "GJCC Spritual Flow - English Audio"
      category: "Christian"
      language: "en-us"
      file_path: "/home/mchu/Music/ZSF/English"
      output_path: "/ntc/tmp/audio-eng.rss"
      filter_extension: ".mp3"
  fr:
    mt-tabor:
      title: "Mt Tabor Service Recordings"
      link: "https://file.ziongjcc.org"
      media_link: "/"
      description: "Mt Tabor Service Recordings"
      category: "Christian"
      language: "fr-pf"
      file_path: "/home/mchu/Videos/MtTabor"
      output_path: "/ntc/tmp/mttabor.rss"
      filter_extension: ".mp4"
  zh:
    videos-all:
      title: "新約教會 錄影檔"
      link: "https://file.ziongjcc.org/Video"
      description: "ACP GJCC 新約教會 錄影檔"
      language: "zh-tw"
      file_path: "/home/mchu/Videos/ZSF"
      filter_extension: ".mp4"
      output_path: "/ntc/tmp/videos.rss"
    audio-chi:
      title: "新約教會 錄音檔"
      link: "https://file.ziongjcc.org/Audio/chinese"
      description: "ACP GJCC 新約教會 錄音檔"
      language: "zh-tw"
      file_path: "/home/mchu/Music/ZSF/Chinese"
      filter_extension: ".mp3"
      output_path: "/ntc/tmp/audio-chi.rss"
folders:
  gjcc:
    title:
      en: "ZSF"
      zh: "新約教會"
      fr: "ZSF"
    link: "https://file.ziongjcc.org"
    base_file_path: "/home/mchu/"
    group: "default"
  mttabor:
    title:
      en: "Mt Tabor"
      zh: "新約教會"
      fr: "Mt Thabor"
    link: "https://file.ziongjcc.org"
    base_file_path: "/home/mchu/Videos/MtTabor"
    group: "mttabor"
